app:
  secret: the_secret
  token-validity-in-seconds: 2592000

spring:
  mvc:
    favicon:
      enabled: false
  resources:
    add-mappings: false
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB